Add Chinese Language File 中国語を追加
kbinani/je2be-gui pull request #9
Opened 2024-09-01 14:40 UTC by TC999

2024-09-01 22:21 UTC, kbinani requested changes
Could you please revert the changes made to `resource/japanese.lang`? The correct character in Japanese for '转换' is '変換'. Thank you.

2024-09-01 22:40 UTC, kbinani commented on resource/chinese.lang
> +"Converting..." = "変換中..."
I believe this line was meant to be `"Converting..." = "转换中..."`. It seems to have been swapped with the entry in `resource/japanese.lang`.

2024-09-01 23:53 UTC, TC999 commented
OK，

2024-11-24 22:12 UTC, kbinani commented
The changes to `.github/workflows/main.yml` are unnecessary, so I will change the target branch of this PR to zh-hans-translation-202411 and merge it for now.

2024-11-24 22:14 UTC, merged

2024-11-24 22:52 UTC, kbinani commented
This change was merged to main in https://github.com/kbinani/je2be-desktop/pull/10
@TC999 Thank you for your contribution